databases:
  - name: ai-news-db
    databaseName: ai_news_db
    user: ai_news_user
    plan: free

services:
  - type: cron
    name: ai-news-daily-job
    env: docker
    schedule: "0 8 * * *" # Runs every day at 8:00 AM UTC
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ai-news-db
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false
      - key: MY_EMAIL
        sync: false
      - key: APP_PASSWORD
        sync: false
